name: 'Retrieve Auth0 Access Token'
description: 'Auth0 login management for your GitHub Actions.'
author: 'Roland Kajatin <roland.kajatin@gmail.com>'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'shield'
  color: 'blue'

# Define your inputs here.
inputs:
  tenant-url:
    description: 'Your Auth0 tenant URL.'
    required: true
  client-id:
    description: 'Your Auth0 client ID.'
    required: true
  client-secret:
    description: 'Your Auth0 client secret.'
    required: true
  audience:
    description: 'Your Auth0 audience.'
    required: false
  grant-type:
    description: 'Your Auth0 grant type.'
    required: false
    default: 'client_credentials'

# Define your outputs here.
outputs:
  ACCESS_TOKEN:
    description: 'Your Auth0 access token.'

runs:
  using: "composite"
  steps:
    - name: Run Auth0 Login Script
      shell: bash
      env:
        TENANT_URL: ${{ inputs.tenant-url }}
        CLIENT_ID: ${{ inputs.client-id }}
        CLIENT_SECRET: ${{ inputs.client-secret }}
        AUDIENCE: ${{ inputs.audience }}
        GRANT_TYPE: ${{ inputs.grant-type }}
      run: ./main.sh
