name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          tenant-url: ${{ secrets.AUTH0_TENANT_URL }}
          client-id: ${{ secrets.AUTH0_CLIENT_ID }}
          client-secret: ${{ secrets.AUTH0_CLIENT_SECRET }}
          audience: ${{ secrets.AUTH0_AUDIENCE }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.access-token }}"
